### ISSUE TITLE
project status and documentation

### ISSUE THREAD

**Issue by buhtz** [apnadkarni/tktreectrl#1]
Can you please use the `README.md` to give some basic informations about the project.

- current status (active, future plans, ...)
- relation and difference to forks: https://sourceforge.net/projects/tktreectrl/ and https://sourceforge.net/projects/tkintertreectrl/
- difference or advantage compared to `tkinter.Treeview`
- a simple example and a screenshot

Thank you very much.

**Comment by apnadkarni** [comment]
Added the README. In  nutshell, this only contains a new nmake based build and some performance fixes. No functional changes. See the original website https://sourceforge.net/projects/tktreectrl/ for documentation, screenshots examples etc. It is very comprehensive. Sorry, no idea about the tkintertreectrl or tkinter.Treeview projects.
